export const DEFAULT_LANGUAGE_OPTIONS=Object.freeze({expectedInputs:[{type:'text',languages:['en']}],expectedOutputs:[{type:'text',languages:['en']}]});
export const MULTIMODAL_LANGUAGE_OPTIONS=Object.freeze({expectedInputs:[{type:'text',languages:['en']},{type:'image'},{type:'audio'}],expectedOutputs:[{type:'text',languages:['en']}]});
export const DEFAULT_WEBLLM_MODEL='Llama-3.2-3B-Instruct-q4f16_1-MLC';
export const DEFAULT_FALLBACK_ENDPOINT='/api/chat';
export const DEFAULT_FALLBACK_TOKEN_BUDGET=4000;
export const DEFAULT_FALLBACK_MAX_TURNS=8;

export function isSupported(g=globalThis){return 'LanguageModel' in g}
export function isWebLLMSupported(g=globalThis){return Boolean(g.navigator?.gpu)}
export function isAbortError(e){return e?.name==='AbortError'}
export async function getAvailability(options=DEFAULT_LANGUAGE_OPTIONS,g=globalThis){return isSupported(g)?g.LanguageModel.availability(options):'unsupported'}

export async function createLocalSession({options=DEFAULT_LANGUAGE_OPTIONS,signal,onProgress=()=>{},onStatus=()=>{},globalObject=globalThis}={}){
 if(!isSupported(globalObject))throw new Error('Chrome Built-in AI is not supported in this browser.');
 if(signal?.aborted)throw new DOMException('The model initialization was aborted.','AbortError');
 const availability=await getAvailability(options,globalObject);
 if(availability==='unavailable')throw new Error('Chrome Built-in AI is unavailable on this device.');
 const needsDownload=availability==='downloadable'||availability==='downloading';
 onStatus({state:needsDownload?'downloading':'ready',source:'native',availability});
 const session=await globalObject.LanguageModel.create({...options,...(signal?{signal}:{}),monitor(m){m.addEventListener('downloadprogress',e=>{const n=Number(e.loaded);const loaded=Number.isFinite(n)?Math.max(0,Math.min(1,n)):0;onProgress({loaded,complete:loaded>=1,extracting:loaded>=1&&needsDownload,source:'native'})})}});
 if(signal?.aborted){session.destroy?.();throw new DOMException('The model initialization was aborted.','AbortError')}
 onStatus({state:'ready',source:'native',availability});return session;
}

export async function promptStreaming(session,prompt,options={}){if(!session?.promptStreaming)throw new TypeError('A valid LanguageModel session is required.');if((typeof prompt!=='string'||!prompt.trim())&&!Array.isArray(prompt))throw new TypeError('Prompt must be non-empty text or a valid multimodal message array.');return session.promptStreaming(prompt,options)}
async function* nativeStream(s,p,o){const stream=await s.promptStreaming(p,o);for await(const c of stream)yield c}
export async function* normalizeStream(stream){let previous='';for await(const raw of stream){const chunk=typeof raw==='string'?raw:String(raw??'');if(!chunk)continue;if(previous&&chunk.startsWith(previous)){const delta=chunk.slice(previous.length);previous=chunk;if(delta)yield delta}else{previous+=chunk;yield chunk}}}
export async function promptToText(session,prompt,onChunk=()=>{},options={}){let out='';for await(const c of normalizeStream(nativeStream(session,prompt,options))){out+=c;onChunk(c,out)}return out}

const isCanvas=v=>typeof HTMLCanvasElement!=='undefined'&&v instanceof HTMLCanvasElement;
const isImage=v=>typeof HTMLImageElement!=='undefined'&&v instanceof HTMLImageElement;
const isBlob=v=>typeof Blob!=='undefined'&&v instanceof Blob;
const isAudioBuffer=v=>typeof AudioBuffer!=='undefined'&&v instanceof AudioBuffer;
const isBinary=v=>v instanceof ArrayBuffer||ArrayBuffer.isView(v);
function toB64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));if(typeof btoa==='function')return btoa(s);if(typeof Buffer!=='undefined')return Buffer.from(bytes).toString('base64');throw new Error('No Base64 encoder is available.')}
async function blobB64(blob,mime){return {mimeType:blob.type||mime,base64Data:toB64(new Uint8Array(await blob.arrayBuffer()))}}
function audioBufferToWavBlob(buffer){const channels=buffer.numberOfChannels,bps=2,dataLength=buffer.length*channels*bps,out=new DataView(new ArrayBuffer(44+dataLength));let p=0;const ws=s=>{for(const c of s)out.setUint8(p++,c.charCodeAt(0))},u16=n=>{out.setUint16(p,n,true);p+=2},u32=n=>{out.setUint32(p,n,true);p+=4};ws('RIFF');u32(36+dataLength);ws('WAVEfmt ');u32(16);u16(1);u16(channels);u32(buffer.sampleRate);u32(buffer.sampleRate*channels*bps);u16(channels*bps);u16(16);ws('data');u32(dataLength);const data=Array.from({length:channels},(_,i)=>buffer.getChannelData(i));for(let i=0;i<buffer.length;i++)for(let c=0;c<channels;c++){const x=Math.max(-1,Math.min(1,data[c][i]));out.setInt16(p,x<0?x*32768:x*32767,true);p+=2}return new Blob([out.buffer],{type:'audio/wav'})}
async function imageB64(v,mime='image/png'){if(isCanvas(v)){const u=v.toDataURL('image/png');return{mimeType:'image/png',base64Data:u.slice(u.indexOf(',')+1)}}if(isImage(v)){if(!v.complete&&v.decode)await v.decode();const c=document.createElement('canvas');c.width=v.naturalWidth||v.width;c.height=v.naturalHeight||v.height;if(!c.width||!c.height)throw new Error('Image has no drawable dimensions.');const x=c.getContext('2d');if(!x)throw new Error('Unable to create image context.');x.drawImage(v,0,0);const u=c.toDataURL(mime);return{mimeType:mime,base64Data:u.slice(u.indexOf(',')+1)}}return null}
export async function mediaPartToBase64(part){if(!part||!['text','image','audio'].includes(part.type))throw new TypeError('Multimodal part must have type text, image, or audio.');if(part.type==='text'||typeof part.value==='string'||part.base64Data)return{...part};if(part.value==null)throw new TypeError(`Missing value for ${part.type} media part.`);const image=await imageB64(part.value,part.mimeType||'image/png');if(image)return{type:'image',...image};if(isBlob(part.value))return{type:part.type,...await blobB64(part.value,part.mimeType||(part.type==='image'?'image/png':'audio/wav'))};if(isAudioBuffer(part.value))return mediaPartToBase64({type:'audio',value:audioBufferToWavBlob(part.value)});if(isBinary(part.value)){const bytes=part.value instanceof ArrayBuffer?new Uint8Array(part.value):new Uint8Array(part.value.buffer,part.value.byteOffset,part.value.byteLength);return{type:part.type,mimeType:part.mimeType||(part.type==='image'?'image/png':'audio/wav'),base64Data:toB64(bytes)}}throw new TypeError(`Unsupported ${part.type} media input.`)}
function normalizeInput(input){if(typeof input==='string')return[{role:'user',content:input}];if(!Array.isArray(input)||!input.length)throw new TypeError('Multimodal input must be non-empty text, parts, or messages.');return input[0]&&typeof input[0]==='object'&&'role' in input[0]?input:[{role:'user',content:input}]}
export async function serializeMultimodalMessages(input){return Promise.all(normalizeInput(input).map(async m=>({role:m.role,content:typeof m.content==='string'?m.content:await Promise.all(m.content.map(mediaPartToBase64))})))}
export function isMultimodalPrompt(input){if(!Array.isArray(input))return false;return input.some(x=>x&&typeof x==='object'&&('role'in x?(Array.isArray(x.content)&&x.content.some(p=>p?.type==='image'||p?.type==='audio')):x.type==='image'||x.type==='audio'))}

export function applySlidingWindow(messages,maxTurns=DEFAULT_FALLBACK_MAX_TURNS){const systems=messages.filter(m=>m.role==='system'),conversation=messages.filter(m=>m.role!=='system'),limit=Math.max(1,Math.floor(maxTurns));return conversation.length<=limit?[...systems,...conversation]:[...systems,...conversation.slice(-limit)]}
let encoderPromise=null;
async function getTokenEncoder(){if(!encoderPromise)encoderPromise=Promise.all([import('js-tiktoken/lite'),import('js-tiktoken/ranks/cl100k_base')]).then(([lib,ranks])=>new lib.Tiktoken(ranks.default));return encoderPromise}
function tokenText(c){if(typeof c==='string')return c;if(!Array.isArray(c))return '';return c.map(p=>p?.type==='text'&&typeof p.value==='string'?p.value:p?.type==='image'?'[image]':p?.type==='audio'?'[audio]':'').join(' ')}
export async function countMessagePayloadTokens(messages){const e=await getTokenEncoder();let total=3;for(const m of messages)total+=3+e.encode(String(m.role??'')).length+e.encode(tokenText(m.content)).length;return total}
export async function applyTokenSlidingWindow(messages,maxTokens=DEFAULT_FALLBACK_TOKEN_BUDGET){const systems=messages.filter(m=>m.role==='system');let conversation=messages.filter(m=>m.role!=='system'),payload=[...systems,...conversation],n=await countMessagePayloadTokens(payload),budget=Math.max(1,Math.floor(maxTokens));while(n>budget&&conversation.length>1){conversation=conversation.slice(1);payload=[...systems,...conversation];n=await countMessagePayloadTokens(payload)}return payload}

async function* responseStream(response){if(!response.body){const text=await response.text();if(text)yield text;return}const reader=response.body.getReader(),decoder=new TextDecoder();while(true){const{done,value}=await reader.read();if(done)break;const text=decoder.decode(value,{stream:true});if(text)yield text}const tail=decoder.decode();if(tail)yield tail}
export async function createWebLLMSession({model=DEFAULT_WEBLLM_MODEL,signal,onProgress=()=>{},onStatus=()=>{},globalObject=globalThis,webllmModule=null}={}){if(!isWebLLMSupported(globalObject))throw new Error('WebGPU is not supported in this browser.');if(signal?.aborted)throw new DOMException('The WebLLM initialization was aborted.','AbortError');const w=webllmModule||await import('@mlc-ai/web-llm');onStatus({state:'downloading',source:'webllm',model});const engine=await w.CreateMLCEngine(model,{initProgressCallback(p){const n=typeof p==='object'&&p?Number(p.progress):Number(p),loaded=Number.isFinite(n)?Math.max(0,Math.min(1,n)):0;onProgress({loaded,complete:loaded>=1,extracting:loaded>=1,source:'webllm'})}});if(signal?.aborted){await engine.unload?.();throw new DOMException('The WebLLM initialization was aborted.','AbortError')}onStatus({state:'ready',source:'webllm',model});return engine}
async function* webllmStream(engine,prompt,options={}){if(options.signal?.aborted)throw new DOMException('The prompt was aborted.','AbortError');const stream=await engine.chat.completions.create({messages:[{role:'user',content:prompt}],stream:true});for await(const c of stream){if(options.signal?.aborted)throw new DOMException('The prompt was aborted.','AbortError');const text=c?.choices?.[0]?.delta?.content;if(text)yield text}}

export class SmartLanguageSession{
 constructor(nativeSession=null,apiEndpoint=DEFAULT_FALLBACK_ENDPOINT,fetchImpl=globalThis.fetch,webllmSession=null,config={}){this.nativeSession=nativeSession;this.apiEndpoint=apiEndpoint||DEFAULT_FALLBACK_ENDPOINT;this.fetchImpl=fetchImpl;this.webllmSession=webllmSession;this.initialPrompts=config.initialPrompts||[];this.fallbackHistory=[];this.maxFallbackTurns=Math.max(1,Math.floor(config.maxFallbackTurns??DEFAULT_FALLBACK_MAX_TURNS));this.maxTokenBudget=Math.max(1,Math.floor(config.maxTokenBudget??DEFAULT_FALLBACK_TOKEN_BUDGET));this.useTokenBudget=config.useTokenBudget!==false;this.onContextOverflow=config.onContextOverflow;this.source=nativeSession?'native':webllmSession?'webllm':'cloud';if(nativeSession&&this.onContextOverflow)nativeSession.addEventListener?.('contextoverflow',this.onContextOverflow)}
 static async create({options={},fallbackEndpoint=DEFAULT_FALLBACK_ENDPOINT,signal,onProgress=()=>{},onStatus=()=>{},globalObject=globalThis,fetchImpl=globalObject.fetch?.bind(globalObject),preferWebLLM=true,webllmModel=DEFAULT_WEBLLM_MODEL,webllmModule=null,maxFallbackTurns=DEFAULT_FALLBACK_MAX_TURNS,maxTokenBudget=DEFAULT_FALLBACK_TOKEN_BUDGET,useTokenBudget=true}={}){const initialPrompts=[];if(typeof options.systemPrompt==='string'&&options.systemPrompt.trim())initialPrompts.push({role:'system',content:options.systemPrompt});if(Array.isArray(options.initialPrompts))initialPrompts.push(...options.initialPrompts);const{systemPrompt:_s,initialPrompts:_i,onContextOverflow:_o,...cap}=options;const nativeOptions={...MULTIMODAL_LANGUAGE_OPTIONS,...cap,expectedInputs:options.expectedInputs??MULTIMODAL_LANGUAGE_OPTIONS.expectedInputs,expectedOutputs:options.expectedOutputs??MULTIMODAL_LANGUAGE_OPTIONS.expectedOutputs,initialPrompts:initialPrompts.length?initialPrompts:undefined};if(isSupported(globalObject))try{const availability=await getAvailability({expectedInputs:nativeOptions.expectedInputs,expectedOutputs:nativeOptions.expectedOutputs,...(nativeOptions.samplingMode!==undefined?{samplingMode:nativeOptions.samplingMode}:{})},globalObject);if(availability!=='unavailable'){const s=await createLocalSession({options:nativeOptions,signal,onProgress,onStatus,globalObject});return new SmartLanguageSession(s,fallbackEndpoint,fetchImpl,null,{initialPrompts,maxFallbackTurns,maxTokenBudget,useTokenBudget,onContextOverflow:options.onContextOverflow})}}catch(e){if(isAbortError(e))throw e;console.warn('Native LanguageModel initialization failed; trying fallback.',e)}if(preferWebLLM&&isWebLLMSupported(globalObject))try{const w=await createWebLLMSession({model:webllmModel,signal,onProgress,onStatus,globalObject,webllmModule});return new SmartLanguageSession(null,fallbackEndpoint,fetchImpl,w,{initialPrompts,maxFallbackTurns,maxTokenBudget,useTokenBudget,onContextOverflow:options.onContextOverflow})}catch(e){if(isAbortError(e))throw e;console.warn('WebLLM initialization failed; using server fallback.',e)}if(signal?.aborted)throw new DOMException('The AI provider initialization was aborted.','AbortError');if(typeof fetchImpl!=='function')throw new Error('No AI provider is available in this environment.');onStatus({state:'ready',source:'cloud',availability:'fallback'});return new SmartLanguageSession(null,fallbackEndpoint,fetchImpl,null,{initialPrompts,maxFallbackTurns,maxTokenBudget,useTokenBudget,onContextOverflow:options.onContextOverflow})}
 async*promptStreaming(prompt,options={}){if((typeof prompt!=='string'||!prompt.trim())&&!Array.isArray(prompt))throw new TypeError('Prompt must be non-empty text or a valid multimodal message array.');if(this.nativeSession){yield*normalizeStream(nativeStream(this.nativeSession,prompt,options));return}if(this.webllmSession&&typeof prompt==='string'){yield*webllmStream(this.webllmSession,prompt,options);return}if(typeof this.fetchImpl!=='function')throw new Error('No HTTP fallback is configured.');if(options.signal?.aborted)throw new DOMException('The prompt was aborted.','AbortError');const incoming=normalizeInput(prompt),history=[...this.initialPrompts,...this.fallbackHistory,...incoming],turnLimited=applySlidingWindow(history,this.maxFallbackTurns),messages=this.useTokenBudget?await applyTokenSlidingWindow(turnLimited,this.maxTokenBudget):turnLimited,response=await this.fetchImpl(this.apiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:await serializeMultimodalMessages(messages)}),...(options.signal?{signal:options.signal}:{})});if(!response.ok)throw new Error(`Fallback API failed with status ${response.status}`);const chunks=[];for await(const c of responseStream(response)){chunks.push(c);yield c}const answer=chunks.join('');this.fallbackHistory=[...this.fallbackHistory,...incoming.filter(m=>m.role!=='system')];if(answer)this.fallbackHistory.push({role:'assistant',content:answer})}
 async promptToText(prompt,onChunk=()=>{},options={}){let out='';for await(const c of this.promptStreaming(prompt,options)){out+=c;onChunk(c,out)}return out}
 async append(messages,options={}){if(!this.nativeSession?.append)throw new Error('append() is only available for Chrome Built-in AI sessions.');return this.nativeSession.append(messages,options)}
 async clone(options={}){if(!this.nativeSession?.clone)throw new Error('clone() is only available for Chrome Built-in AI sessions.');return new SmartLanguageSession(await this.nativeSession.clone(options),this.apiEndpoint,this.fetchImpl,null,{initialPrompts:this.initialPrompts,maxFallbackTurns:this.maxFallbackTurns,maxTokenBudget:this.maxTokenBudget,useTokenBudget:this.useTokenBudget,onContextOverflow:this.onContextOverflow})}
 get contextUsage(){return this.nativeSession?.contextUsage}get contextWindow(){return this.nativeSession?.contextWindow}get contextUsageRatio(){const u=this.contextUsage,w=this.contextWindow;return Number.isFinite(u)&&Number.isFinite(w)&&w>0?u/w:undefined}
 measureContextUsage(input,options={}){if(!this.nativeSession?.measureContextUsage)throw new Error('measureContextUsage() is only available for Chrome Built-in AI sessions.');return this.nativeSession.measureContextUsage(input,options)}
 addEventListener(...a){return this.nativeSession?.addEventListener?.(...a)}removeEventListener(...a){return this.nativeSession?.removeEventListener?.(...a)}
 async destroy(){if(this.nativeSession&&this.onContextOverflow)this.nativeSession.removeEventListener?.('contextoverflow',this.onContextOverflow);this.nativeSession?.destroy?.();await this.webllmSession?.unload?.();this.nativeSession=null;this.webllmSession=null;this.fallbackHistory=[]}
}
export const createSmartSession=(options={})=>SmartLanguageSession.create(options);
export function createHybridRunner({localSession,cloudPrompt}){if(typeof cloudPrompt!=='function')throw new TypeError('cloudPrompt must be a function.');return async function run(prompt,{preferLocal=true,onChunk=()=>{},options={}}={}){if(preferLocal&&localSession)try{return await localSession.promptToText(prompt,onChunk,options)}catch(e){if(isAbortError(e))throw e;console.warn('Local AI failed; using cloud fallback.',e)}const result=await cloudPrompt(prompt);onChunk(result,result);return result}}
