import { tokenService } from './token-service';
import type { Availability, InitialPrompt, MediaInput, MultimodalMessage, MultimodalPart, MultimodalPrompt, NativeLanguageModel, Progress, PromptOptions, SessionOptions, SmartCreateOptions, Status, WebLLMEngine } from './types';

export const DEFAULT_LANGUAGE_OPTIONS: Readonly<SessionOptions> = Object.freeze({ expectedInputs: [{ type: 'text', languages: ['en'] }], expectedOutputs: [{ type: 'text', languages: ['en'] }] });
export const MULTIMODAL_LANGUAGE_OPTIONS: Readonly<SessionOptions> = Object.freeze({ expectedInputs: [{ type: 'text', languages: ['en'] }, { type: 'image' }, { type: 'audio' }], expectedOutputs: [{ type: 'text', languages: ['en'] }] });
export const DEFAULT_WEBLLM_MODEL = 'Llama-3.2-3B-Instruct-q4f16_1-MLC';
export const DEFAULT_FALLBACK_ENDPOINT = '/api/chat';
export const DEFAULT_FALLBACK_TOKEN_BUDGET = 4000;
export const DEFAULT_FALLBACK_MAX_TURNS = 8;

export function isSupported(globalObject: any = globalThis): boolean { return 'LanguageModel' in globalObject; }
export function isWebLLMSupported(globalObject: any = globalThis): boolean { return Boolean(globalObject.navigator?.gpu); }
export function isAbortError(error: unknown): boolean { return (error instanceof Error && error.name === 'AbortError') || (error as { name?: string } | null)?.name === 'AbortError'; }
export async function getAvailability(options: SessionOptions = DEFAULT_LANGUAGE_OPTIONS, globalObject: any = globalThis): Promise<Availability | 'unsupported'> { return isSupported(globalObject) ? globalObject.LanguageModel.availability(options) : 'unsupported'; }

export async function createLocalSession({ options = DEFAULT_LANGUAGE_OPTIONS, signal, onProgress = () => undefined, onStatus = () => undefined, globalObject = globalThis }: { options?: SessionOptions; signal?: AbortSignal; onProgress?: (p: Progress) => void; onStatus?: (s: Status) => void; globalObject?: any } = {}): Promise<NativeLanguageModel> {
  if (!isSupported(globalObject)) throw new Error('Chrome Built-in AI is not supported in this browser.');
  if (signal?.aborted) throw new DOMException('The model initialization was aborted.', 'AbortError');
  const availability = await getAvailability(options, globalObject);
  if (availability === 'unavailable') throw new Error('Chrome Built-in AI is unavailable on this device.');
  const needsDownload = availability === 'downloadable' || availability === 'downloading';
  onStatus({ state: needsDownload ? 'downloading' : 'ready', source: 'native', availability });
  const session = await globalObject.LanguageModel.create({ ...options, ...(signal ? { signal } : {}), monitor(monitor: EventTarget) {
    monitor.addEventListener('downloadprogress', (event) => {
      const value = Number((event as Event & { loaded?: number }).loaded);
      const loaded = Number.isFinite(value) ? Math.max(0, Math.min(1, value)) : 0;
      onProgress({ loaded, complete: loaded >= 1, extracting: loaded >= 1 && needsDownload, source: 'native' });
    });
  } });
  if (signal?.aborted) { session.destroy?.(); throw new DOMException('The model initialization was aborted.', 'AbortError'); }
  onStatus({ state: 'ready', source: 'native', availability });
  return session;
}

export async function promptStreaming(session: NativeLanguageModel, prompt: MultimodalPrompt, options: PromptOptions = {}): Promise<ReadableStream<string>> {
  if (!session?.promptStreaming) throw new TypeError('A valid LanguageModel session is required.');
  if ((typeof prompt !== 'string' || !prompt.trim()) && !Array.isArray(prompt)) throw new TypeError('Prompt must be non-empty text or a valid multimodal message array.');
  return session.promptStreaming(prompt, options);
}

async function* nativeStream(session: NativeLanguageModel, prompt: MultimodalPrompt, options: PromptOptions = {}): AsyncGenerator<string> { const stream = await session.promptStreaming(prompt, options); for await (const chunk of stream as AsyncIterable<string>) yield chunk; }
export async function* normalizeStream(stream: AsyncIterable<string>): AsyncGenerator<string> { let previous = ''; for await (const raw of stream) { const chunk = typeof raw === 'string' ? raw : String(raw ?? ''); if (!chunk) continue; if (previous && chunk.startsWith(previous)) { const delta = chunk.slice(previous.length); previous = chunk; if (delta) yield delta; } else { previous += chunk; yield chunk; } } }
export async function promptToText(session: NativeLanguageModel, prompt: MultimodalPrompt, onChunk: (chunk: string, accumulated: string) => void = () => undefined, options: PromptOptions = {}): Promise<string> { let output = ''; for await (const chunk of normalizeStream(nativeStream(session, prompt, options))) { output += chunk; onChunk(chunk, output); } return output; }

const isCanvas = (value: unknown): value is HTMLCanvasElement => typeof HTMLCanvasElement !== 'undefined' && value instanceof HTMLCanvasElement;
const isImage = (value: unknown): value is HTMLImageElement => typeof HTMLImageElement !== 'undefined' && value instanceof HTMLImageElement;
const isBlob = (value: unknown): value is Blob => typeof Blob !== 'undefined' && value instanceof Blob;
const isAudioBuffer = (value: unknown): value is AudioBuffer => typeof AudioBuffer !== 'undefined' && value instanceof AudioBuffer;
const isBinary = (value: unknown): value is ArrayBuffer | ArrayBufferView => value instanceof ArrayBuffer || ArrayBuffer.isView(value);
function toBase64(bytes: Uint8Array): string { let binary = ''; for (let i = 0; i < bytes.length; i += 0x8000) binary += String.fromCharCode(...bytes.subarray(i, Math.min(i + 0x8000, bytes.length))); if (typeof btoa === 'function') return btoa(binary); if (typeof Buffer !== 'undefined') return Buffer.from(bytes).toString('base64'); throw new Error('No Base64 encoder is available.'); }
async function blobToBase64(blob: Blob, mime: string): Promise<{ mimeType: string; base64Data: string }> { return { mimeType: blob.type || mime, base64Data: toBase64(new Uint8Array(await blob.arrayBuffer())) }; }
function audioBufferToWavBlob(buffer: AudioBuffer): Blob { const channels = buffer.numberOfChannels; const dataLength = buffer.length * channels * 2; const view = new DataView(new ArrayBuffer(44 + dataLength)); let offset = 0; const s = (x: string) => { for (const c of x) view.setUint8(offset++, c.charCodeAt(0)); }; const u16 = (x: number) => { view.setUint16(offset, x, true); offset += 2; }; const u32 = (x: number) => { view.setUint32(offset, x, true); offset += 4; }; s('RIFF'); u32(36 + dataLength); s('WAVEfmt '); u32(16); u16(1); u16(channels); u32(buffer.sampleRate); u32(buffer.sampleRate * channels * 2); u16(channels * 2); u16(16); s('data'); u32(dataLength); const data = Array.from({ length: channels }, (_, c) => buffer.getChannelData(c)); for (let i = 0; i < buffer.length; i++) for (let c = 0; c < channels; c++) { const sample = Math.max(-1, Math.min(1, data[c][i])); view.setInt16(offset, sample < 0 ? sample * 32768 : sample * 32767, true); offset += 2; } return new Blob([view.buffer], { type: 'audio/wav' }); }
async function imageToBase64(value: HTMLCanvasElement | HTMLImageElement, mime = 'image/png') { if (isCanvas(value)) { const dataUrl = value.toDataURL('image/png'); return { mimeType: 'image/png', base64Data: dataUrl.slice(dataUrl.indexOf(',') + 1) }; } if (isImage(value)) { if (!value.complete && value.decode) await value.decode(); const canvas = document.createElement('canvas'); canvas.width = value.naturalWidth || value.width; canvas.height = value.naturalHeight || value.height; if (!canvas.width || !canvas.height) throw new Error('Image has no drawable dimensions.'); const context = canvas.getContext('2d'); if (!context) throw new Error('Unable to create image context.'); context.drawImage(value, 0, 0); const dataUrl = canvas.toDataURL(mime); return { mimeType: mime, base64Data: dataUrl.slice(dataUrl.indexOf(',') + 1) }; } return null; }

export async function mediaPartToBase64(part: MultimodalPart): Promise<MultimodalPart> {
  if (!part || !['text', 'image', 'audio'].includes(part.type)) throw new TypeError('Multimodal part must have type text, image, or audio.');
  if (part.type === 'text' || typeof part.value === 'string' || part.base64Data) return { ...part };
  if (part.value == null) throw new TypeError(`Missing value for ${part.type} media part.`);
  const image = isCanvas(part.value) || isImage(part.value) ? await imageToBase64(part.value, part.mimeType || 'image/png') : null;
  if (image) return { type: 'image', ...image };
  if (isBlob(part.value)) return { type: part.type, ...await blobToBase64(part.value, part.mimeType || (part.type === 'image' ? 'image/png' : 'audio/wav')) };
  if (isAudioBuffer(part.value)) return mediaPartToBase64({ type: 'audio', value: audioBufferToWavBlob(part.value) });
  if (isBinary(part.value)) { const bytes = part.value instanceof ArrayBuffer ? new Uint8Array(part.value) : new Uint8Array(part.value.buffer, part.value.byteOffset, part.value.byteLength); return { type: part.type, mimeType: part.mimeType || (part.type === 'image' ? 'image/png' : 'audio/wav'), base64Data: toBase64(bytes) }; }
  throw new TypeError(`Unsupported ${part.type} media input.`);
}
function normalizeInput(input: MultimodalPrompt): MultimodalMessage[] { if (typeof input === 'string') return [{ role: 'user', content: input }]; if (!Array.isArray(input) || !input.length) throw new TypeError('Multimodal input must be non-empty text, parts, or messages.'); const first = input[0] as any; return first && typeof first === 'object' && 'role' in first ? input as MultimodalMessage[] : [{ role: 'user', content: input as MultimodalPart[] }]; }
export async function serializeMultimodalMessages(input: MultimodalPrompt): Promise<MultimodalMessage[]> { return Promise.all(normalizeInput(input).map(async (message) => ({ role: message.role, content: typeof message.content === 'string' ? message.content : await Promise.all(message.content.map(mediaPartToBase64)) })));
}
export function applySlidingWindow(messages: MultimodalMessage[], maxTurns = DEFAULT_FALLBACK_MAX_TURNS): MultimodalMessage[] { const systems = messages.filter((m) => m.role === 'system'); const conversation = messages.filter((m) => m.role !== 'system'); const limit = Math.max(1, Math.floor(maxTurns)); return conversation.length <= limit ? [...systems, ...conversation] : [...systems, ...conversation.slice(-limit)]; }
export async function countMessagePayloadTokens(messages: MultimodalMessage[]): Promise<number> { return tokenService.countPayloadTokens(messages); }
export async function applyTokenSlidingWindow(messages: MultimodalMessage[], maxTokens = DEFAULT_FALLBACK_TOKEN_BUDGET): Promise<MultimodalMessage[]> { const systems = messages.filter((m) => m.role === 'system'); let conversation = messages.filter((m) => m.role !== 'system'); const budget = Math.max(1, Math.floor(maxTokens)); while (conversation.length > 1) { const payload = [...systems, ...conversation]; if (await countMessagePayloadTokens(payload) <= budget) return payload; conversation = conversation.slice(1); } return [...systems, ...conversation]; }
async function* responseStream(response: Response): AsyncGenerator<string> { if (!response.body) { const text = await response.text(); if (text) yield text; return; } const reader = response.body.getReader(); const decoder = new TextDecoder(); try { while (true) { const { done, value } = await reader.read(); if (done) break; const text = decoder.decode(value, { stream: true }); if (text) yield text; } const tail = decoder.decode(); if (tail) yield tail; } finally { reader.releaseLock(); } }

export async function createWebLLMSession({ model = DEFAULT_WEBLLM_MODEL, signal, onProgress = () => undefined, onStatus = () => undefined, globalObject = globalThis, webllmModule = null }: { model?: string; signal?: AbortSignal; onProgress?: (p: Progress) => void; onStatus?: (s: Status) => void; globalObject?: any; webllmModule?: any } = {}): Promise<WebLLMEngine> { if (!isWebLLMSupported(globalObject)) throw new Error('WebGPU is not supported in this browser.'); if (signal?.aborted) throw new DOMException('The WebLLM initialization was aborted.', 'AbortError'); const webllm = webllmModule || await import('@mlc-ai/web-llm'); onStatus({ state: 'downloading', source: 'webllm', model }); const engine = await webllm.CreateMLCEngine(model, { initProgressCallback(progress: unknown) { const value = typeof progress === 'object' && progress ? Number((progress as { progress?: number }).progress) : Number(progress); const loaded = Number.isFinite(value) ? Math.max(0, Math.min(1, value)) : 0; onProgress({ loaded, complete: loaded >= 1, extracting: loaded >= 1, source: 'webllm' }); } }); if (signal?.aborted) { await engine.unload?.(); throw new DOMException('The WebLLM initialization was aborted.', 'AbortError'); } onStatus({ state: 'ready', source: 'webllm', model }); return engine as WebLLMEngine; }
async function* webllmStream(engine: WebLLMEngine, prompt: string, options: PromptOptions = {}): AsyncGenerator<string> { if (options.signal?.aborted) throw new DOMException('The prompt was aborted.', 'AbortError'); const stream = await engine.chat.completions.create({ messages: [{ role: 'user', content: prompt }], stream: true }); for await (const chunk of stream) { if (options.signal?.aborted) throw new DOMException('The prompt was aborted.', 'AbortError'); const text = chunk?.choices?.[0]?.delta?.content; if (text) yield text; } }

interface SmartConfig { initialPrompts: InitialPrompt[]; maxFallbackTurns: number; maxTokenBudget: number; useTokenBudget: boolean; onContextOverflow?: (event: Event) => void }
export class SmartLanguageSession {
  readonly nativeSession: NativeLanguageModel | null; readonly apiEndpoint: string; readonly fetchImpl: typeof fetch | undefined; readonly webllmSession: WebLLMEngine | null; readonly initialPrompts: InitialPrompt[]; readonly fallbackHistory: MultimodalMessage[] = []; readonly maxFallbackTurns: number; readonly maxTokenBudget: number; readonly useTokenBudget: boolean; readonly onContextOverflow?: (event: Event) => void; readonly source: 'native' | 'webllm' | 'cloud'; private destroyed = false;
  constructor(nativeSession: NativeLanguageModel | null = null, apiEndpoint = DEFAULT_FALLBACK_ENDPOINT, fetchImpl: typeof fetch | undefined = globalThis.fetch?.bind(globalThis), webllmSession: WebLLMEngine | null = null, config: Partial<SmartConfig> = {}) { this.nativeSession = nativeSession; this.apiEndpoint = apiEndpoint || DEFAULT_FALLBACK_ENDPOINT; this.fetchImpl = fetchImpl; this.webllmSession = webllmSession; this.initialPrompts = config.initialPrompts || []; this.maxFallbackTurns = Math.max(1, Math.floor(config.maxFallbackTurns ?? DEFAULT_FALLBACK_MAX_TURNS)); this.maxTokenBudget = Math.max(1, Math.floor(config.maxTokenBudget ?? DEFAULT_FALLBACK_TOKEN_BUDGET)); this.useTokenBudget = config.useTokenBudget !== false; this.onContextOverflow = config.onContextOverflow; this.source = nativeSession ? 'native' : webllmSession ? 'webllm' : 'cloud'; if (nativeSession && this.onContextOverflow) nativeSession.addEventListener?.('contextoverflow', this.onContextOverflow as EventListener); tokenService.prefetch(); }
  static async create({ options = {}, fallbackEndpoint = DEFAULT_FALLBACK_ENDPOINT, signal, onProgress = () => undefined, onStatus = () => undefined, globalObject = globalThis, fetchImpl = globalObject.fetch?.bind(globalObject), preferWebLLM = true, webllmModel = DEFAULT_WEBLLM_MODEL, webllmModule = null, maxFallbackTurns = DEFAULT_FALLBACK_MAX_TURNS, maxTokenBudget = DEFAULT_FALLBACK_TOKEN_BUDGET, useTokenBudget = true }: SmartCreateOptions = {}): Promise<SmartLanguageSession> {
    const initialPrompts: InitialPrompt[] = []; if (typeof options.systemPrompt === 'string' && options.systemPrompt.trim()) initialPrompts.push({ role: 'system', content: options.systemPrompt }); if (Array.isArray(options.initialPrompts)) initialPrompts.push(...options.initialPrompts);
    const { systemPrompt: _systemPrompt, initialPrompts: _initialPrompts, onContextOverflow: _overflow, maxTokenBudget: _maxTokenBudget, ...capabilities } = options;
    const nativeOptions: SessionOptions = { ...MULTIMODAL_LANGUAGE_OPTIONS, ...capabilities, expectedInputs: options.expectedInputs ?? MULTIMODAL_LANGUAGE_OPTIONS.expectedInputs, expectedOutputs: options.expectedOutputs ?? MULTIMODAL_LANGUAGE_OPTIONS.expectedOutputs, initialPrompts: initialPrompts.length ? initialPrompts : undefined };
    if (isSupported(globalObject)) try { const availability = await getAvailability(nativeOptions, globalObject); if (availability !== 'unavailable') { const session = await createLocalSession({ options: nativeOptions, signal, onProgress, onStatus, globalObject }); return new SmartLanguageSession(session, fallbackEndpoint, fetchImpl, null, { initialPrompts, maxFallbackTurns, maxTokenBudget, useTokenBudget, onContextOverflow: options.onContextOverflow }); } } catch (error) { if (isAbortError(error)) throw error; console.warn('Native LanguageModel initialization failed; trying fallback.', error); }
    if (preferWebLLM && isWebLLMSupported(globalObject)) try { const engine = await createWebLLMSession({ model: webllmModel, signal, onProgress, onStatus, globalObject, webllmModule }); return new SmartLanguageSession(null, fallbackEndpoint, fetchImpl, engine, { initialPrompts, maxFallbackTurns, maxTokenBudget, useTokenBudget, onContextOverflow: options.onContextOverflow }); } catch (error) { if (isAbortError(error)) throw error; console.warn('WebLLM initialization failed; using server fallback.', error); }
    if (signal?.aborted) throw new DOMException('The AI provider initialization was aborted.', 'AbortError'); if (typeof fetchImpl !== 'function') throw new Error('No AI provider is available in this environment.'); onStatus({ state: 'ready', source: 'cloud', availability: 'fallback' }); return new SmartLanguageSession(null, fallbackEndpoint, fetchImpl, null, { initialPrompts, maxFallbackTurns, maxTokenBudget, useTokenBudget, onContextOverflow: options.onContextOverflow });
  }
  async *promptStreaming(prompt: MultimodalPrompt, options: PromptOptions = {}): AsyncGenerator<string> { if (this.destroyed) throw new Error('Session has been destroyed.'); if ((typeof prompt !== 'string' || !prompt.trim()) && !Array.isArray(prompt)) throw new TypeError('Prompt must be non-empty text or a valid multimodal message array.'); if (this.nativeSession) { yield* normalizeStream(nativeStream(this.nativeSession, prompt, options)); return; } if (this.webllmSession && typeof prompt === 'string') { yield* webllmStream(this.webllmSession, prompt, options); return; } if (typeof this.fetchImpl !== 'function') throw new Error('No HTTP fallback is configured.'); if (options.signal?.aborted) throw new DOMException('The prompt was aborted.', 'AbortError'); const incoming = normalizeInput(prompt); const history = [...this.initialPrompts, ...this.fallbackHistory, ...incoming]; const turnLimited = applySlidingWindow(history, this.maxFallbackTurns); const messages = this.useTokenBudget ? await applyTokenSlidingWindow(turnLimited, this.maxTokenBudget) : turnLimited; const response = await this.fetchImpl(this.apiEndpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: await serializeMultimodalMessages(messages) }), ...(options.signal ? { signal: options.signal } : {}) }); if (!response.ok) throw new Error(`Fallback API failed with status ${response.status}`); const chunks: string[] = []; for await (const chunk of responseStream(response)) { chunks.push(chunk); yield chunk; } const answer = chunks.join(''); this.fallbackHistory.push(...incoming.filter((m) => m.role !== 'system')); if (answer) this.fallbackHistory.push({ role: 'assistant', content: answer }); }
  async promptToText(prompt: MultimodalPrompt, onChunk: (chunk: string, accumulated: string) => void = () => undefined, options: PromptOptions = {}): Promise<string> { let output = ''; for await (const chunk of this.promptStreaming(prompt, options)) { output += chunk; onChunk(chunk, output); } return output; }
  async append(messages: MultimodalPrompt, options: { signal?: AbortSignal } = {}): Promise<void> { if (!this.nativeSession?.append) throw new Error('append() is only available for Chrome Built-in AI sessions.'); await this.nativeSession.append(messages, options); }
  async clone(options: { signal?: AbortSignal } = {}): Promise<SmartLanguageSession> { if (!this.nativeSession?.clone) throw new Error('clone() is only available for Chrome Built-in AI sessions.'); return new SmartLanguageSession(await this.nativeSession.clone(options), this.apiEndpoint, this.fetchImpl, null, { initialPrompts: this.initialPrompts, maxFallbackTurns: this.maxFallbackTurns, maxTokenBudget: this.maxTokenBudget, useTokenBudget: this.useTokenBudget, onContextOverflow: this.onContextOverflow }); }
  get contextUsage(): number | undefined { return this.nativeSession?.contextUsage; }
  get contextWindow(): number | undefined { return this.nativeSession?.contextWindow; }
  get contextUsageRatio(): number | undefined { const usage = this.contextUsage; const window = this.contextWindow; return Number.isFinite(usage) && Number.isFinite(window) && window! > 0 ? usage! / window! : undefined; }
  measureContextUsage(input: MultimodalPrompt, options: PromptOptions = {}): number | Promise<number> { if (!this.nativeSession?.measureContextUsage) throw new Error('measureContextUsage() is only available for Chrome Built-in AI sessions.'); return this.nativeSession.measureContextUsage(input, options); }
  addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void { this.nativeSession?.addEventListener(type, listener, options); }
  removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void { this.nativeSession?.removeEventListener(type, listener, options); }
  async destroy(): Promise<void> { if (this.destroyed) return; this.destroyed = true; if (this.nativeSession) { this.nativeSession.removeEventListener?.('contextoverflow', this.onContextOverflow as EventListener); this.nativeSession.destroy?.(); } if (this.webllmSession?.unload) await this.webllmSession.unload(); }
}
export function createSmartSession(options: SmartCreateOptions = {}): Promise<SmartLanguageSession> { return SmartLanguageSession.create(options); }
export type { Availability, InitialPrompt, MediaInput, MultimodalMessage, MultimodalPart, MultimodalPrompt, PromptOptions, SessionOptions, SmartCreateOptions, Progress, Status } from './types';
