export type Availability='unavailable'|'downloadable'|'downloading'|'available';
export type LanguageModelSamplingMode='most-predictable'|'predictable'|'slightly-predictable'|'balanced'|'slightly-creative'|'creative'|'most-creative';
export interface InitialPrompt{role:'system'|'user'|'assistant';content:string;prefix?:boolean}
export interface SessionOptions{systemPrompt?:string;initialPrompts?:InitialPrompt[];expectedInputs?:Array<{type:'text'|'image'|'audio';languages?:string[]}>;expectedOutputs?:Array<{type:'text';languages?:string[]}>;samplingMode?:LanguageModelSamplingMode;topK?:number;temperature?:number;onContextOverflow?:(event:Event)=>void}
export type MediaInput=Blob|HTMLCanvasElement|HTMLImageElement|AudioBuffer|ArrayBuffer|ArrayBufferView;
export interface MultimodalPart{type:'text'|'image'|'audio';value?:string|MediaInput;base64Data?:string;mimeType?:string}
export interface MultimodalMessage{role:'user'|'assistant'|'system';content:string|MultimodalPart[]}
export type MultimodalPrompt=string|MultimodalPart[]|MultimodalMessage[];
export type LanguageModelPrompt=MultimodalPrompt;
export interface LanguageModelPromptOptions{responseConstraint?:Record<string,unknown>;omitResponseConstraintInput?:boolean;signal?:AbortSignal}
export interface LanguageModelAppendOptions{signal?:AbortSignal}
export interface LanguageModelCloneOptions{signal?:AbortSignal}
export interface SmartSessionStatus{state:string;source:'native'|'webllm'|'cloud';availability?:string;model?:string}
export interface SmartSessionProgress{loaded:number;complete:boolean;extracting:boolean;source:'native'|'webllm'}
export interface SmartSessionCreateOptions{options?:SessionOptions;fallbackEndpoint?:string;signal?:AbortSignal;onProgress?:(progress:SmartSessionProgress)=>void;onStatus?:(status:SmartSessionStatus)=>void;globalObject?:any;fetchImpl?:typeof fetch;preferWebLLM?:boolean;webllmModel?:string;webllmModule?:any;maxFallbackTurns?:number;maxTokenBudget?:number;useTokenBudget?:boolean}
export declare class LanguageModel extends EventTarget{static create(options?:SessionOptions&{signal?:AbortSignal;monitor?:(monitor:EventTarget)=>void;initialPrompts?:InitialPrompt[]}):Promise<LanguageModel>;static availability(options?:SessionOptions):Promise<Availability>;prompt(input:LanguageModelPrompt,options?:LanguageModelPromptOptions):Promise<string>;promptStreaming(input:LanguageModelPrompt,options?:LanguageModelPromptOptions):ReadableStream<string>;append(input:LanguageModelPrompt,options?:LanguageModelAppendOptions):Promise<void>;clone(options?:LanguageModelCloneOptions):Promise<LanguageModel>;measureContextUsage(input:LanguageModelPrompt,options?:LanguageModelPromptOptions):Promise<number>;countPromptTokens(input:LanguageModelPrompt,options?:LanguageModelPromptOptions):Promise<number>;readonly contextUsage:number;readonly contextWindow:number;destroy():void}
export declare class SmartLanguageSession{constructor(nativeSession?:LanguageModel|null,apiEndpoint?:string,fetchImpl?:typeof fetch,webllmSession?:any,config?:any);static create(options?:SmartSessionCreateOptions):Promise<SmartLanguageSession>;readonly source:'native'|'webllm'|'cloud';readonly contextUsage:number|undefined;readonly contextWindow:number|undefined;readonly contextUsageRatio:number|undefined;promptStreaming(prompt:MultimodalPrompt,options?:LanguageModelPromptOptions):AsyncGenerator<string>;promptToText(prompt:MultimodalPrompt,onChunk?:(chunk:string,accumulated:string)=>void,options?:LanguageModelPromptOptions):Promise<string>;append(messages:LanguageModelPrompt,options?:LanguageModelAppendOptions):Promise<void>;clone(options?:LanguageModelCloneOptions):Promise<SmartLanguageSession>;measureContextUsage(input:LanguageModelPrompt,options?:LanguageModelPromptOptions):number|Promise<number>;addEventListener(type:string,listener:EventListenerOrEventListenerObject,options?:boolean|AddEventListenerOptions):any;removeEventListener(type:string,listener:EventListenerOrEventListenerObject,options?:boolean|EventListenerOptions):any;destroy():Promise<void>}
export declare const DEFAULT_LANGUAGE_OPTIONS:Readonly<SessionOptions>;export declare const MULTIMODAL_LANGUAGE_OPTIONS:Readonly<SessionOptions>;export declare const DEFAULT_WEBLLM_MODEL:string;export declare const DEFAULT_FALLBACK_ENDPOINT:string;export declare const DEFAULT_FALLBACK_TOKEN_BUDGET:number;export declare const DEFAULT_FALLBACK_MAX_TURNS:number;
export declare function isSupported(globalObject?:any):boolean;export declare function isWebLLMSupported(globalObject?:any):boolean;export declare function isAbortError(error:unknown):boolean;export declare function getAvailability(options?:SessionOptions,globalObject?:any):Promise<Availability|'unsupported'>;export declare function createLocalSession(options?:any):Promise<LanguageModel>;export declare function createWebLLMSession(options?:any):Promise<any>;export declare function createSmartSession(options?:SmartSessionCreateOptions):Promise<SmartLanguageSession>;export declare function promptStreaming(session:LanguageModel,prompt:LanguageModelPrompt,options?:LanguageModelPromptOptions):Promise<ReadableStream<string>>;export declare function promptToText(session:LanguageModel,prompt:LanguageModelPrompt,onChunk?:(chunk:string,accumulated:string)=>void,options?:LanguageModelPromptOptions):Promise<string>;export declare function normalizeStream(stream:AsyncIterable<string>):AsyncGenerator<string>;export declare function mediaPartToBase64(part:MultimodalPart):Promise<MultimodalPart>;export declare function serializeMultimodalMessages(input:MultimodalPrompt):Promise<MultimodalMessage[]>;export declare function isMultimodalPrompt(input:MultimodalPrompt):boolean;export declare function applySlidingWindow(messages:MultimodalMessage[],maxTurns?:number):MultimodalMessage[];export declare function countMessagePayloadTokens(messages:MultimodalMessage[]):Promise<number>;export declare function applyTokenSlidingWindow(messages:MultimodalMessage[],maxTokens?:number):Promise<MultimodalMessage[]>;export declare function createHybridRunner(options:{localSession?:SmartLanguageSession|null;cloudPrompt:(prompt:string)=>Promise<string>}):any;
declare global{interface Window{ai?:{languageModel:typeof LanguageModel}}}
